name: 'Publish Changelog'
description: 'Publish the latest changelog from CHANGELOG.md via webhook (e.g. discord).'
branding:
  icon: send
  color: blue
inputs:
  webhook-url:
    description: 'The webhook url that to be called'
    required: true
  changelog:
    description: 'File location for the CHANGELOG.md file'
    required: false
    default: './CHANGELOG.md'
  format-date:
    description: 'Format for a date.'
    required: false
    default: 'Y-m-d'
  format-version:
    description: 'Format for the version line (available variables: version, date)'
    required: false
    default: '**{{version}} - {{date}}**'
  format-type:
    description: 'Format for the type of change (added, changed, fixed, ...)'
    required: false
    default: '*{{type}}*'
  format-change:
    description: 'Format for a line of change'
    required: false
    default: '• {{text}}'
runs:
  using: 'node16'
  main: 'action/index.js'