name: Test

on: [workflow_dispatch]

jobs:
  test:
    name: Test Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: derpierre65/publish-changelog-action@main
        with:
          webhook-url: ${{ secrets.PUBLISH_CHANGELOG_WEBHOOK_URL }}